version: '3'
services: 
    python:
        build: .
        networks:
            - whomentionstock_network

networks:
    whomentionstock_network:
        external: true
        name: custom_whomentionstock_network